[package]
name = "kattis"
version = "0.1.0"
authors = ["Yoeri Otten <yoeri@otten.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
